server:
  port: 8763
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/gannan17?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: HL921124
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: springcloudarticle
eureka:
  client:
    service-url:
      defaultZone: http://user:HL921124@localhost:8761/eureka
feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
